services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/php83/Dockerfile
    volumes:
      - ./src:/var/www/html
    expose:
      - 9000

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php-fpm
