name: Build Docker Images

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}    

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get Git commit SHA
        id: git_sha
        run: echo "::set-output name=SHA::$(git rev-parse --short HEAD)"

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/nginx/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ secrets.DOCKER_SERVICE_USERNAME }}/nginx:${{ steps.git_sha.outputs.SHA }}-${{ matrix.platform }}

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/php83/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ secrets.DOCKER_SERVICE_USERNAME }}/php83:${{ steps.git_sha.outputs.SHA }}-${{ matrix.platform }}