name: notify-pipeline-status

on:
    workflow_call:
      inputs:
        pipeline:
            required: true
            type: string
        status_on_success_push: 
            required: true
            type: string
        status_on_success_update_chart: 
            required: true
            type: string
        error_message_push: 
            required: true
            type: string
        error_output_push: 
            required: true
            type: string
        error_message_update_chart: 
            required: true
            type: string
        error_output_update_chart: 
            required: true
            type: string

    workflow_run:
      workflows: ["publish-docker-images"]
      types: [completed] #requested

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
    
      - name: Update Helm Chart Values Image Tag
        run: |
          echo "${{ inputs.status_on_success_push }}"
          echo "${{ inputs.status_on_success_update_chart }}"
          echo "${{ inputs.pipeline }}"
          echo "${{ inputs.error_message_push }}"
          echo "${{ inputs.error_output_push }}"
          echo "${{ inputs.error_message_update_chart }}"
          echo "${{ inputs.error_output_update_chart }}"

      - name: Send Discord notification on success
        if: ${{ inputs.status_on_success_push == 'success' && inputs.status_on_success_update_chart == 'success' }}
        uses: Ilshidur/action-discord@master
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "${{ inputs.pipeline }} Build and Publish: Success"

      - name: Send Discord notification on failure
        if: ${{ inputs.status_on_success_push == 'failure' || inputs.status_on_success_update_chart == 'failure' }}
        uses: Ilshidur/action-discord@master
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "${{ inputs.pipeline }} Build and Publish: Failure ${{ inputs.error_message_push }} ${{ inputs.error_output_push }} ${{ inputs.error_message_update_chart }} ${{ inputs.error_output_update_chart }}"