name: publish-docker-images

on:
  workflow_call:
    inputs:
      platforms:
        required: true
        type: string
      git_sha:
        required: true
        type: string

  workflow_run:
    workflows: ["build-docker-images"]
    types: [completed] #requested

jobs:
  on-success-push:
    runs-on: ubuntu-latest
    environment: development    
    steps:
      - name: Debug Outputs
        run: |
          echo "Platforms: ${{ inputs.platforms }}"
          echo "Git SHA: ${{ inputs.git_sha }}"          

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Docker Image (Nginx)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/nginx/Dockerfile
          platforms: ${{ inputs.platforms }}
          tags:  ${{ secrets.DOCKER_USERNAME }}/capstone-vulnerable-nginx:${{ inputs.git_sha }}-${{ inputs.platforms }}
          push: true

      - name: Publish Docker Image (PHP83)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/php83/Dockerfile
          platforms: ${{ inputs.platforms }}
          tags:  ${{ secrets.DOCKER_USERNAME }}/capstone-vulnerable-php83:${{ inputs.git_sha }}-${{ inputs.platforms }}
          push: true

  on-success-update-chart:
    runs-on: ubuntu-latest
    environment: development    
    steps:
      - name: Debug Outputs
        run: |
          echo "Platforms: ${{ inputs.platforms }}"
          echo "Git SHA: ${{ inputs.git_sha }}"          

      - name: Checkout Helm Chart Repository
        uses: actions/checkout@v2
        with:
          repository: elysiansky/capstone-chart-vulnerable-php83
          ref: main # Or use the branch/tag you want to update
          token: ${{ secrets.HELM_CHART_PERSONAL_ACCESS_TOKEN }}
          path: ./capstone-chart-vulnerable-php83

      # Update the Helm chart's values.yaml tag: VALUE with the latest Git SHA VALUE
      - name: Update Helm Chart Values Image Tag
        run: |          
          IMAGE_TAG=$(cat values.yaml | grep tag: | cut -d ":" -f 2 | tr -d ' " ')
          sed -i "s/$IMAGE_TAG/${{ inputs.git_sha }}/g" capstone-chart-vulnerable-php83/values.yaml
        working-directory: ./capstone-vulnerable-php83


      # Commit and push the changes to the Helm chart repository
      - name: Commit and Push Changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Update image tag with latest Git SHA"
          git push