name: Publish Docker Images

on:
  push:
    branches:
      - main
      - development

jobs:
  # Empty job to satisfy workflow requirement
  dummy:
    runs-on: ubuntu-latest
    needs: []  # No dependencies
    steps:
      - name: Empty Step  # Add this empty step
        run: echo "Workaround placeholder to satisfy github action requirement"  # Or any other harmless command

  publish:
    runs-on: ubuntu-latest
    environment: development
    needs: build  # This job depends on the successful completion of the "build" job in build.yaml

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Docker Image (Nginx)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/nginx/Dockerfile
          platforms: ${{ needs.build.outputs.PLATFORMS }}  # Get platforms from build job output
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/capstone-vulnerable-nginx:${{ needs.build.outputs.GIT_SHA }}-${{ needs.build.outputs.PLATFORMS }}
          push: true  # Enable push for this job

      - name: Publish Docker Image (PHP83)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/php83/Dockerfile
          platforms: ${{ needs.build.outputs.PLATFORMS }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/capstone-vulnerable-php83:${{ needs.build.outputs.SHA }}-${{ needs.build.outputs.PLATFORMS }}
          push: true  # Enable push for this job
