# name: Publish Docker Images

# on:
#   push:
#     branches:
#       - main
#   workflow_run:
#     workflows: ["Build Docker Images"]
#     types:
#       - completed

# env:
#   DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#   DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
#   HELM_CHART_PERSONAL_ACCESS_TOKEN: ${{ secrets.HELM_CHART_PERSONAL_ACCESS_TOKEN }}

# jobs:
#   publish:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Push Docker image to Docker Hub
#         run: docker push ${{ secrets.DOCKER_USERNAME }}/php83:${{ steps.git_sha.outputs.SHA }}-${{ matrix.platform }}
