name: Publish Docker Images

on:
  workflow_call:
    inputs:
      PLATFORMS:
        required: true
        type: string
      GIT_SHA:
        required: true
        type: string
    outputs:
      PUBLISH_STATUS:
        value: ${{ jobs.publish.outputs.PUBLISH_STATUS }}

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Docker Image (Nginx)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/nginx/Dockerfile
          platforms: ${{ inputs.PLATFORMS }}  # Get platforms from build job output
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/capstone-vulnerable-nginx:${{ inputs.GIT_SHA }}-${{ inputs.PLATFORMS }}
          push: true  # Enable push for this job

      - name: Publish Docker Image (PHP83)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/php83/Dockerfile
          platforms: ${{ inputs.PLATFORMS }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/capstone-vulnerable-php83:${{ inputs.GIT_SHA }}-${{ inputs.PLATFORMS }}
          push: true  # Enable push for this job
