name: Publish Docker Images (Reusable)

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ inputs.dockerfile_path }}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/{{ inputs.image_name }}:${{ github.sha }}-${{ inputs.platforms }}
